# Minimal conda environment with python, pip and uv and windows Make file support.
# Dependencies are managed via pyproject.toml using uv
# Install it: conda env create -f environment.yml
name: ocxwiki
channels:
  - conda-forge
  - msys2 # for m2-grep
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - m2w64-make # GNU mMake for windows
  - m2-grep # Grep for windows. For Makefile sh
  - m2-gawk # awk for windows. for Makefile sh
  # uv is typically installed via pipx on the host; install into the env if desired:
  # - uv
